apiVersion: v1
kind: Service
metadata:
  name: post-srv
spec:
  type: NodePort
  selector:
    app: posts #this is a label applied to the pod like a css selector
  ports: # - in yaml refers to an array
    - name: posts
      protocol: TCP
      port: 4000 #this is the port for the node port service, it will then redirect this, but usually port and tport are the same
      targetPort: 4000 #the place we actually want to send traffic to

